### ISSUE TITLE
Provide license keys to students

### ISSUE THREAD

**Issue by Ludee** [htw-pv3/weather-data#16]
I experimented with serial mails to send the private keys.
`(30 x 2 x Strg+C+V) < (learn to serial mail with word, excel and outlook)`

I'm not sure if it worked. Please give feedback.

**Comment by Ludee** [comment]
x = 1h

**Comment by Patrickhs** [comment]
Keys worked fine for both PVSol and Polysun. Thank you!

**Comment by FaidoEwald** [comment]
> 
> 
> I experimented with serial mails to send the private keys.
> `(30 x 2 x Strg+C+V) < (learn to serial mail with word, excel and outlook)`

Ein gute Tutorial zu SerienEmails habe ich [hier](https://www.youtube.com/watch?v=BGlscTE3854) gefunden!

**Comment by khelfen** [comment]
Worked fine, thank you!

**Comment by Ludee** [comment]
> Aber PVSol meldet bei der Registrierung:
> .. Server nicht erreicht.

Das sollte ein Verbindungsproblem sein. Internet an? Firewall?

**Comment by FaidoEwald** [comment]
> Das sollte ein Verbindungsproblem sein. Internet an? Firewall?

Geklärt! Über einen WLAN Hotspot des Handys verlief die Registrierung problemlos.

**Comment by baytar-muhammed** [comment]
Just registered ! Both of them worked .

**Comment by mauricio-ocampo** [comment]
It worked!
