### ISSUE TITLE
reformulation of the task

### ISSUE THREAD

**Issue by nailend** [htw-pv3/weather-data#19]
As there was some confusion about the task and @Ludee already stated that there have been similar situations before I thought about rephrasing the task in a way I would probably understand it.

This Issue can go on for the following tasks as well. 
This might help @htw-pv3/sose2020 this semester and evenutally the group of next year.

**Comment by khelfen** [comment]
This can be closed, right?

**Comment by nailend** [comment]
It would be nice to have some feedback. Thats why I would reopen it for a couple of days.
