### ISSUE TITLE
Having Trouble with "Aufgabe #6 Python Environment und Jupyter" - please help!

### ISSUE THREAD

**Issue by FaidoEwald** [htw-pv3/weather-data#23]
Having Trouble in executing the jupyter-skript "pv3_sonnja_db_wr.ipynb". Die zweite Zelle kreiert mir nach der Passworteingabe den untenstehenden Fehler. Hat Jemand eine Idee wie ich den behoben bekomme? Ich habe das environment mit Hilfe von dem Skript "requirements.yml" ausgeührt

    "Please provide connection parameters to database:

    Hit [Enter] to take defaults

    password: ········

    ---------------------------------------------------------------------------ModuleNotFoundError                       Traceback (most recent call last)<ipython-input-2-b862db6d62e6> in <module>     21      22 # start session---> 23 con = postgres_session()

    <ipython-input-2-b862db6d62e6> in postgres_session()     16                                                   host,     17                                                   port,---> 18                                                   database)).connect()     19     print('Password correct! Database connection established.')     20     return con

    C:\Anaconda3\lib\site-packages\sqlalchemy\engine\__init__.py in create_engine(*args, **kwargs)    477     strategy = kwargs.pop("strategy", default_strategy)    478     strategy = strategies.strategies[strategy]--> 479     return strategy.create(*args, **kwargs)    480     481 

    C:\Anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py in create(self, name_or_url, **kwargs)     85                 if k in kwargs:     86                     dbapi_args[k] = pop_kwarg(k)---> 87             dbapi = dialect_cls.dbapi(**dbapi_args)     88      89         dialect_args["dbapi"] = dbapi

    C:\Anaconda3\lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py in dbapi(cls)    735     @classmethod    736     def dbapi(cls):--> 737         import psycopg2    738     739         return psycopg2

    ModuleNotFoundError: No module named 'psycopg2'"

**Comment by FaidoEwald** [comment]
Zwischenzeitlich habe ich ein das Modul "psycopg2" installiert bekommen und diverse andere WEge versucht das Skript in jupyter notebook auszuführen. Aber die "Database Connection" schlägt fehl, egal was ich mache... Aktuell erschlägt mich diese Fehlermeldung:

> Please provide connection parameters to database:
> Hit [Enter] to take defaults
> password: ········
> 
> ---------------------------------------------------------------------------
> OperationalError                          Traceback (most recent call last)
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
>    2275         try:
> -> 2276             return fn()
>    2277         except dialect.dbapi.Error as e:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in unique_connection(self)
>     302         """
> --> 303         return _ConnectionFairy._checkout(self)
>     304 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _checkout(cls, pool, threadconns, fairy)
>     772         if not fairy:
> --> 773             fairy = _ConnectionRecord.checkout(pool)
>     774 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in checkout(cls, pool)
>     491     def checkout(cls, pool):
> --> 492         rec = pool._do_get()
>     493         try:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
>     138                 with util.safe_reraise():
> --> 139                     self._dec_overflow()
>     140         else:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
>      67             if not self.warn_only:
> ---> 68                 compat.reraise(exc_type, exc_value, exc_tb)
>      69         else:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in reraise(tp, value, tb, cause)
>     152             raise value.with_traceback(tb)
> --> 153         raise value
>     154 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
>     135             try:
> --> 136                 return self._create_connection()
>     137             except:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _create_connection(self)
>     307 
> --> 308         return _ConnectionRecord(self)
>     309 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __init__(self, pool, connect)
>     436         if connect:
> --> 437             self.__connect(first_connect_check=True)
>     438         self.finalize_callback = deque()
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
>     651             self.starttime = time.time()
> --> 652             connection = pool._invoke_creator(self)
>     653             pool.logger.debug("Created new connection %r", connection)
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py in connect(connection_record)
>     113                             return connection
> --> 114                 return dialect.connect(*cargs, **cparams)
>     115 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py in connect(self, *cargs, **cparams)
>     488     def connect(self, *cargs, **cparams):
> --> 489         return self.dbapi.connect(*cargs, **cparams)
>     490 
> 
> C:\Anaconda3\lib\site-packages\psycopg2\__init__.py in connect(dsn, connection_factory, cursor_factory, **kwargs)
>     125     dsn = _ext.make_dsn(dsn, **kwargs)
> --> 126     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
>     127     if cursor_factory is not None:
> 
> OperationalError: 
> 
> The above exception was the direct cause of the following exception:
> 
> OperationalError                          Traceback (most recent call last)
> <ipython-input-2-b862db6d62e6> in <module>
>      21 
>      22 # start session
> ---> 23 con = postgres_session()
> 
> <ipython-input-2-b862db6d62e6> in postgres_session()
>      16                                                   host,
>      17                                                   port,
> ---> 18                                                   database)).connect()
>      19     print('Password correct! Database connection established.')
>      20     return con
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in connect(self, **kwargs)
>    2207         """
>    2208 
> -> 2209         return self._connection_cls(self, **kwargs)
>    2210 
>    2211     @util.deprecated(
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in __init__(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events)
>     101                 connection
>     102                 if connection is not None
> --> 103                 else engine.raw_connection()
>     104             )
>     105             self.__transaction = None
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in raw_connection(self, _connection)
>    2305         """
>    2306         return self._wrap_pool_connect(
> -> 2307             self.pool.unique_connection, _connection
>    2308         )
>    2309 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
>    2278             if connection is None:
>    2279                 Connection._handle_dbapi_exception_noconnection(
> -> 2280                     e, dialect, self
>    2281                 )
>    2282             else:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _handle_dbapi_exception_noconnection(cls, e, dialect, engine)
>    1545             util.raise_from_cause(newraise, exc_info)
>    1546         elif should_wrap:
> -> 1547             util.raise_from_cause(sqlalchemy_exception, exc_info)
>    1548         else:
>    1549             util.reraise(*exc_info)
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in raise_from_cause(exception, exc_info)
>     396     exc_type, exc_value, exc_tb = exc_info
>     397     cause = exc_value if exc_value is not exception else None
> --> 398     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>     399 
>     400 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in reraise(tp, value, tb, cause)
>     150             value.__cause__ = cause
>     151         if value.__traceback__ is not tb:
> --> 152             raise value.with_traceback(tb)
>     153         raise value
>     154 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py in _wrap_pool_connect(self, fn, connection)
>    2274         dialect = self.dialect
>    2275         try:
> -> 2276             return fn()
>    2277         except dialect.dbapi.Error as e:
>    2278             if connection is None:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in unique_connection(self)
>     301 
>     302         """
> --> 303         return _ConnectionFairy._checkout(self)
>     304 
>     305     def _create_connection(self):
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _checkout(cls, pool, threadconns, fairy)
>     771     def _checkout(cls, pool, threadconns=None, fairy=None):
>     772         if not fairy:
> --> 773             fairy = _ConnectionRecord.checkout(pool)
>     774 
>     775             fairy._pool = pool
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in checkout(cls, pool)
>     490     @classmethod
>     491     def checkout(cls, pool):
> --> 492         rec = pool._do_get()
>     493         try:
>     494             dbapi_connection = rec.get_connection()
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
>     137             except:
>     138                 with util.safe_reraise():
> --> 139                     self._dec_overflow()
>     140         else:
>     141             return self._do_get()
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\langhelpers.py in __exit__(self, type_, value, traceback)
>      66             self._exc_info = None  # remove potential circular references
>      67             if not self.warn_only:
> ---> 68                 compat.reraise(exc_type, exc_value, exc_tb)
>      69         else:
>      70             if not compat.py3k and self._exc_info and self._exc_info[1]:
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py in reraise(tp, value, tb, cause)
>     151         if value.__traceback__ is not tb:
>     152             raise value.with_traceback(tb)
> --> 153         raise value
>     154 
>     155     def u(s):
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\impl.py in _do_get(self)
>     134         if self._inc_overflow():
>     135             try:
> --> 136                 return self._create_connection()
>     137             except:
>     138                 with util.safe_reraise():
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in _create_connection(self)
>     306         """Called by subclasses to create a new ConnectionRecord."""
>     307 
> --> 308         return _ConnectionRecord(self)
>     309 
>     310     def _invalidate(self, connection, exception=None, _checkin=True):
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __init__(self, pool, connect)
>     435         self.__pool = pool
>     436         if connect:
> --> 437             self.__connect(first_connect_check=True)
>     438         self.finalize_callback = deque()
>     439 
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\pool\base.py in __connect(self, first_connect_check)
>     650         try:
>     651             self.starttime = time.time()
> --> 652             connection = pool._invoke_creator(self)
>     653             pool.logger.debug("Created new connection %r", connection)
>     654             self.connection = connection
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py in connect(connection_record)
>     112                         if connection is not None:
>     113                             return connection
> --> 114                 return dialect.connect(*cargs, **cparams)
>     115 
>     116             creator = pop_kwarg("creator", connect)
> 
> C:\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py in connect(self, *cargs, **cparams)
>     487 
>     488     def connect(self, *cargs, **cparams):
> --> 489         return self.dbapi.connect(*cargs, **cparams)
>     490 
>     491     def create_connect_args(self, url):
> 
> C:\Anaconda3\lib\site-packages\psycopg2\__init__.py in connect(dsn, connection_factory, cursor_factory, **kwargs)
>     124 
>     125     dsn = _ext.make_dsn(dsn, **kwargs)
> --> 126     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
>     127     if cursor_factory is not None:
>     128         conn.cursor_factory = cursor_factory
> 
> OperationalError: (psycopg2.OperationalError) 
> (Background on this error at: http://sqlalche.me/e/e3q8)
> 
>

**Comment by Ludee** [comment]
> ModuleNotFoundError: No module named 'psycopg2'"

Das Package [**psycopg2** ](https://pypi.org/project/psycopg2/) scheint nicht installiert oder fehlerhaft zu sein. Es ist dafür bekannt.

Kannst du bitte dokumentieren, warum es so lange gedauert hat und was letzendlich den Fehler behoben hat.

**Comment by FaidoEwald** [comment]
Mittlerweile habe ich die Probleme beimm Aufsetzen des "environments: d_py37_pv bzw. d_py37_vis" in den Griff bekommen. Hauptgrund: Der Download des Packets/Modules "psycopg2" schlug mehrmals fehl. Daher mein **Hinweis: alle Module müssen vollständig heruntergeladen werden. Manchmal überspringt der Installer ein fehlerhaftes Packet und das fällt dann zunächst nicht auf**
