### ISSUE TITLE
Correct metadata information

### ISSUE THREAD

**Issue by khelfen** [htw-pv3/weather-data#3]
### Wrong parameters in my Metadata "Resources":
- There are some wrong "types" in the following files.
- example:
-  wrong. [...wr1_v140_Kh.json L.108](https://github.com/htw-pv3/weather-data/blob/873e4102755933a3a8b436a34d83d1afbc72f455/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr1_v140_KH.json#L108)
- correct [sql-script-5 L.48](https://github.com/htw-pv3/weather-data/blob/708cbed3e0800c09ed3358f6ee06440eafa9b6d0/postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql#L48)

### Choose one of the following:

 - [x] [einleuchtend_wrdata_2015_wr1_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr1_v140_KH.json) @nailend 
 - [x] [einleuchtend_wrdata_2015_wr2_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr2_v140_KH.json) @khelfen 
 - [x] [einleuchtend_wrdata_2015_wr3_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr3_v140_KH.json) @khelfen 
 - [x] [einleuchtend_wrdata_2015_wr4_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr4_v140_KH.json) @TheBlackBlade 
 - [x] [einleuchtend_wrdata_2015_wr5_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/einleuchtend_wrdata_2015_wr5_v140_KH.json) @Braak-1991 
 - [x] [htw_wetter_weatherdata_2015_v140_KH.json](https://github.com/htw-pv3/weather-data/blob/MyMetaData/helfenbein_kilian/helfenbein_kilian_metadata/htw_wetter_weatherdata_2015_v140_KH.json) @Lamelot 

#### Please correct the fields "name" and "type"
* ***Clone my [Branch](https://github.com/htw-pv3/weather-data/tree/MyMetaData/helfenbein_kilian) and create your own!***
* add "p_dc", "istberechnet" and "pr" column and the last two columns
* The correct values can be found in [htw_pv3_postgresql_05_setup_tables_and_import_data.sql](https://github.com/htw-pv3/weather-data/blob/master/postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql)
* When I didn't know something I wrote "unknown". Feel free to fill unknown fields if you know it!
* Copy Paste "Context" Fields from [Moodle](https://moodle.htw-berlin.de/mod/assign/view.php?id=663435) and add them into the .json

#### Please follow this example
* [Good Example for wr1](https://github.com/htw-pv3/weather-data/pull/6/files)

 ### Finish with a Pull Request on my [Branch](https://github.com/htw-pv3/weather-data/tree/MyMetaData/helfenbein_kilian) and me as reviewer:

 - [x] WR1
 - [x] WR2
 - [x] WR3
 - [x] WR4 
 - [x] WR5
 - [x] Weather Data

### Miscellaneous
* Please ***assign yourself per edit directly into this post*** with your initials like @khelfen regarding the files before you start working on them to prevent redundance!
* You can make a subbranch of this branch by using the following commands (replace the ** with your chosen file wr1,wr2, etc) or checkout [stackoverflow](https://stackoverflow.com/a/32391944):
`git checkout MyMetaData/helfenbein_kilian `
`git checkout -b feature/rework_metadata_*****#3`

### After all work above is done

- [x] add missing p_dc in .json @khelfen 
- [x] transfer into [htw_pv3_postgresql_05_setup_tables_and_import_data.sql](https://github.com/htw-pv3/weather-data/blob/master/postgresql/htw_pv3_postgresql_05_setup_tables_and_import_data.sql) @khelfen

**Comment by nailend** [comment]
@khelfen what do you mean by Error?

**Comment by khelfen** [comment]
Falsche Parameter meinte ich^^

**Comment by TheBlackBlade** [comment]
@nailend @khelfen Important note: @Braak-1991 noticed, that the entire for p_dc is missing from the raw JSON files provided by @khelfen 
I don't see them added in wr1 file, please check again

**Comment by khelfen** [comment]
Good note. Will add them 👍

**Comment by nailend** [comment]
> @nailend @khelfen Important note: @Braak-1991 noticed, that the entire for p_dc is missing from the raw JSON files provided by @khelfen
> I don't see them added in wr1 file, please check again

thx

**Comment by Ludee** [comment]
I will rename the filenames and merge a PR to publish the first part of the metadata. Push your open code now.

**Comment by Ludee** [comment]
Make sure to follow the git flow:
`git status`
`git commit`
`git pull` 
-> merge conflict?
`git mergetool`

**Comment by khelfen** [comment]
@Ludee Not sure what to do now. Should I close my Branch and start a new one from master if i want to work on something?
