### ISSUE TITLE
Fix related gaps during day in data_analysis

### ISSUE THREAD

**Issue by JohannesBru** [htw-pv3/weather-data#39]
Currently the SQL Skript 07 (data_analysis) does not declare gaps which start before sunrise and end after sunset as during day = TRUE.

**Comment by JohannesBru** [comment]
@Ludee 
I created a branch and fixed the issue but im currently not allowed to push the branch to the git repository.

**Comment by Ludee** [comment]
Great enhancement and well implemented. Thanks @JohannesBru
