### ISSUE TITLE
Fix check  gaps in fill_gaps line 494

### ISSUE THREAD

**Issue by JohannesBru** [htw-pv3/weather-data#40]
In SQL Skript 10 "fill_gaps" looks like there is an "AND is gap" statement Missing in line 494.

Leads to wrong count of "Minuten am Tag" in the created "VIEW" "pv3_weather_allwr_2015_filled_stat_view" See attached Picture.

![allwr_filled_stat_view_before_analysis_fix](https://user-images.githubusercontent.com/84442264/168445478-008cd0a0-068b-49c8-9c45-ee75253cc858.PNG)

**Comment by Ludee** [comment]
Great Bugfix 🌈
